// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios'
import type {
  ChatApiChatPostData,
  ChatApiChatPostError,
  ChatApiChatPostResponse
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Chat
 */
export const chatApiChatPost = <ThrowOnError extends boolean = false>(
  options: Options<ChatApiChatPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ChatApiChatPostResponse,
    ChatApiChatPostError,
    ThrowOnError
  >({
    ...options,
    url: '/api/chat'
  })
}
